# [Info]
site_name: Nothing except Notes # 左上角标题
site_url: https://ziyu-tian.github.io
site_author: Ziyu Tian
site_description: Ziyu Tian's Website

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: teal # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: Switch to dark mode # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: en # 一些提示性的文字
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Ziyu-Tian/ziyu-tian.github.io # 右上角点击跳转的链接
repo_name: ziyu-tian.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2023 Ziyu Tian # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github # 鼠标悬浮提示
      link: https://github.com/Ziyu-Tian
      name: GitHub | Ziyu Tian

# [Navigation]
nav:
    - Notes:
        - 'NOTES/index.md'
        - Stage1_Notes:
            - Job Application: 'NOTES/Stage_1/1000/Job_Application.md'
            - Placement Year: 'NOTES/Stage_1/1000/Placement.md'
            - Engineering Mathematics: 'NOTES/Stage_1/1001/EngineeringMath.md'
            - C Programing Basic: 'NOTES/Stage_1/Coding/C.md'
            - MATLAB Basic: 'NOTES/Stage_1/Coding/Matlab.md'
            - Python Data Analysis: 'NOTES/Stage_1/Coding/PythonDataAnalysis.md'
        - Electronics Notes:
            - Fundamentals of Electric Circuits: 'NOTES/Electronics/FundamentalElectricCircuits.md'
        - Stage2_Notes:
            - Semiconductors Devices: 'NOTES/Stage_2/semiconductor.md'
            - Signals and Communication: 'NOTES/Stage_2/signalsAndCommunication.md'
            - Computer Systems and Microprocessors: 'NOTES/Stage_2/computerSystems.md'
            - Analogue Electronics: 'NOTES/Stage_2/analogElectronic.md'
            - Microprocessors: 'NOTES/Stage_2/microProcessors.md'
            - Digital Electronics: 'NOTES/Stage_2/digitalElectronics.md'
            - VHDL Basics: 'NOTES/Stage_2/vhdl.md'
            - Statistical Method: 'NOTES/Stage_2/statisticalMethod.md'
            - AC Electrical Power: 'NOTES/Stage_2/acElectrical.md'
            - Automatic Control Systems: 'NOTES/Stage_2/automaticControl.md'
        - Stage3_Notes:
            - Industrial Control and PLC: 'NOTES/Stage_3/Industrial_Control.md'
            - introduction to Business Law: 'NOTES/Stage_3/Introduction_to_Law.md'
            - Digital Signal Processing: 'NOTES/Stage_3/Digital_Signal_Process.md'

    - Dev: 
        - 'DEV/index.md'
        - Time & Space Complexity: 'DEV/TimeComplexity.md'
        - Static modifier in C: 'DEV/StaticInC.md'
        - Pass-by-Value & Pass-by-Reference: 'DEV/ValueRefPass.md'
        - Bit Operation: 'DEV/BitOperation.md'
    - Blog:
        - 'BLOGS/index.md'
        - Blogs_Zero: 'BLOGS/BlogsZero.md' 
        - Thoughts 22/08/22: 'BLOGS/Thoughts_220822.md' 
        - Thoughts 24/08/22: 'BLOGS/Thoughts_240822.md'
        - Poem Thoughts 26/08/22: 'BLOGS/Literature_260822.md'


# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - zh
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  - live2d-widget/dist/autoload.js
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
